// Comprehensive Korean Name Database 2024-2025
// Based on latest popularity data and traditional Saju analysis
// Total: 200 names (100 male + 100 female) across all five elements

export const EXPANDED_KOREAN_NAMES = {
  wood: {
    male: [
      // Most Popular 2024-2025 Wood Element Names
      { korean: '민준', romanization: 'Min-jun', englishSound: 'min-joon', meaning: 'Quick to learn and handsome', story: 'This name combines the wisdom of a scholar with natural charm, perfect for someone who grows like a strong tree.', popularity: 95 },
      { korean: '건우', romanization: 'Gun-woo', englishSound: 'gun-woo', meaning: 'Strong and excellent', story: 'Like a mighty oak that provides shelter, this name represents strength rooted in kindness and protection of others.', popularity: 88 },
      { korean: '지호', romanization: 'Ji-ho', englishSound: 'jee-ho', meaning: 'Wise and great', story: 'This name carries the essence of ancient wisdom combined with modern greatness, like a sage who guides with gentle strength.', popularity: 85 },
      { korean: '재민', romanization: 'Jae-min', englishSound: 'jay-min', meaning: 'Talented and quick', story: 'Like bamboo that bends but never breaks, this name represents resilient talent that adapts and grows.', popularity: 82 },
      { korean: '현준', romanization: 'Hyun-jun', englishSound: 'hyun-joon', meaning: 'Virtuous and talented', story: 'This name embodies the virtue of ancient scholars combined with natural talent, growing like a wise old tree.', popularity: 80 },
      { korean: '민성', romanization: 'Min-seong', englishSound: 'min-sung', meaning: 'Quick and sincere', story: 'Like morning dew that nourishes new growth, this name represents sincere effort that leads to natural success.', popularity: 78 },
      { korean: '지민', romanization: 'Ji-min', englishSound: 'jee-min', meaning: 'Wise and quick', story: 'This name flows like a spring breeze through forest leaves, representing wisdom that moves with natural grace.', popularity: 76 },
      { korean: '성민', romanization: 'Seong-min', englishSound: 'sung-min', meaning: 'Sincere and quick', story: 'Like a tree that grows straight toward the light, this name represents honest growth and natural integrity.', popularity: 74 },
      { korean: '준영', romanization: 'Jun-yeong', englishSound: 'joon-young', meaning: 'Talented and prosperous', story: 'This name represents the prosperity that comes from nurturing talent, like a garden that flourishes with care.', popularity: 72 },
      { korean: '민우', romanization: 'Min-woo', englishSound: 'min-woo', meaning: 'Quick and excellent', story: 'Like a young pine that reaches boldly toward the sky, this name embodies quick excellence and natural ambition.', popularity: 70 },
      { korean: '재현', romanization: 'Jae-hyun', englishSound: 'jay-hyun', meaning: 'Talented and virtuous', story: 'This name combines artistic talent with moral virtue, like a master craftsman who creates beauty with integrity.', popularity: 68 },
      { korean: '지우', romanization: 'Ji-woo', englishSound: 'jee-woo', meaning: 'Wise and gentle rain', story: 'Like gentle rain that awakens sleeping seeds, this name represents wisdom that nurtures growth in others.', popularity: 66 },
      { korean: '건희', romanization: 'Gun-hui', englishSound: 'gun-hee', meaning: 'Strong and bright', story: 'This name shines like sunlight through forest canopy, representing strength that illuminates and guides others.', popularity: 64 },
      { korean: '민제', romanization: 'Min-je', englishSound: 'min-jay', meaning: 'Quick and talented', story: 'Like a swift stream that carves its path through rock, this name represents talent that finds its way naturally.', popularity: 62 },
      { korean: '준수', romanization: 'Jun-soo', englishSound: 'joon-soo', meaning: 'Talented and excellent', story: 'This name embodies the excellence that comes from cultivating natural talent, like a master gardener tends his trees.', popularity: 60 },
      { korean: '현민', romanization: 'Hyun-min', englishSound: 'hyun-min', meaning: 'Virtuous and quick', story: 'Like a bamboo shoot that grows with righteous purpose, this name represents virtue expressed through swift action.', popularity: 58 },
      { korean: '지성', romanization: 'Ji-seong', englishSound: 'jee-sung', meaning: 'Wise and sincere', story: 'This name grows like ancient wisdom rooted in sincere practice, representing knowledge that comes from honest effort.', popularity: 56 },
      { korean: '민기', romanization: 'Min-gi', englishSound: 'min-gee', meaning: 'Quick and energetic', story: 'Like wind through spring leaves, this name represents energetic intelligence that brings life and movement to everything it touches.', popularity: 54 },
      { korean: '재우', romanization: 'Jae-woo', englishSound: 'jay-woo', meaning: 'Talented and excellent', story: 'This name embodies excellence that grows from natural talent, like a tree that bears beautiful fruit season after season.', popularity: 52 },
      { korean: '준호', romanization: 'Jun-ho', englishSound: 'joon-ho', meaning: 'Talented and great', story: 'Like a magnificent tree that provides shade for generations, this name represents talent that creates lasting greatness.', popularity: 50 },
      // K-pop inspired names
      { korean: '태형', romanization: 'Tae-hyung', englishSound: 'tay-hyung', meaning: 'Great virtue', story: 'Like a strong tree that grows with great virtue, this name represents someone who stands tall with moral strength and natural charisma.', popularity: 85, kpopMember: { group: 'BTS', memberName: 'V' } },
      { korean: '남준', romanization: 'Nam-jun', englishSound: 'nam-joon', meaning: 'South talented', story: 'This name embodies talent that flows like a river from the south, bringing wisdom and leadership like ancient scholars.', popularity: 82, kpopMember: { group: 'BTS', memberName: 'RM' } },
      { korean: '윤기', romanization: 'Yoon-gi', englishSound: 'yoon-gee', meaning: 'Prosperous foundation', story: 'Like bamboo that grows from a prosperous foundation, this name represents success built on solid roots and creative expression.', popularity: 78, kpopMember: { group: 'BTS', memberName: 'Suga' } }
    ],
    female: [
      // Most Popular 2024-2025 Wood Element Names  
      { korean: '서연', romanization: 'Seo-yeon', englishSound: 'suh-yun', meaning: 'Beautiful lotus from the west', story: 'Like a lotus that blooms pure and beautiful from muddy waters, this name represents grace that emerges from challenges.', popularity: 95 },
      { korean: '지우', romanization: 'Ji-woo', englishSound: 'jee-woo', meaning: 'Wise and gentle rain', story: 'This name embodies the gentle wisdom that nourishes growth, like spring rain that brings life to sleeping gardens.', popularity: 92 },
      { korean: '채원', romanization: 'Chae-won', englishSound: 'chay-won', meaning: 'Colorful garden', story: 'Like a garden in full bloom, this name represents someone who brings beauty and variety to the world around them.', popularity: 89 },
      { korean: '지유', romanization: 'Ji-yoo', englishSound: 'jee-yoo', meaning: 'Wise and abundant', story: 'Like rich earth that nurtures seeds into flowers, this name embodies wisdom that brings abundance through patient nurturing.', popularity: 86 },
      { korean: '서우', romanization: 'Seo-woo', englishSound: 'suh-woo', meaning: 'Auspicious rain', story: 'This name flows like blessed rain that brings prosperity, representing good fortune that nurtures growth in all areas of life.', popularity: 83 },
      { korean: '지민', romanization: 'Ji-min', englishSound: 'jee-min', meaning: 'Wise and quick', story: 'Like a mountain stream that knows exactly where to flow, this name embodies quick wisdom that finds the most beautiful path forward.', popularity: 80 },
      { korean: '예린', romanization: 'Ye-rin', englishSound: 'yeh-rin', meaning: 'Beautiful and wise', story: 'This name grows like a wise tree that bears beautiful flowers, representing beauty that comes from inner wisdom and grace.', popularity: 77 },
      { korean: '하린', romanization: 'Ha-rin', englishSound: 'ha-rin', meaning: 'Beautiful sky', story: 'Like the vast sky that nurtures all growth below, this name represents beauty that provides space for others to flourish.', popularity: 74 },
      { korean: '지원', romanization: 'Ji-won', englishSound: 'jee-won', meaning: 'Wise source', story: 'This name flows like a pure spring that feeds a forest, representing wisdom that becomes a source of life for others.', popularity: 71 },
      { korean: '서진', romanization: 'Seo-jin', englishSound: 'suh-jin', meaning: 'Auspicious and precious', story: 'Like a precious flower that blooms in the most auspicious season, this name represents value that grows naturally over time.', popularity: 68 },
      { korean: '예은', romanization: 'Ye-eun', englishSound: 'yeh-eun', meaning: 'Beautiful grace', story: 'This name embodies the grace of a willow tree that dances beautifully with every breeze, representing elegant strength.', popularity: 65 },
      { korean: '지현', romanization: 'Ji-hyun', englishSound: 'jee-hyun', meaning: 'Wise and virtuous', story: 'Like an ancient tree that has grown wise through seasons, this name represents virtue that deepens with understanding.', popularity: 62 },
      { korean: '채은', romanization: 'Chae-eun', englishSound: 'chay-eun', meaning: 'Colorful grace', story: 'This name blooms like a garden where every flower has its own grace, representing diverse talents unified in beauty.', popularity: 59 },
      { korean: '서영', romanization: 'Seo-yeong', englishSound: 'suh-young', meaning: 'Auspicious and prosperous', story: 'Like a tree that prospers in the most favorable conditions, this name represents fortune that grows with proper nurturing.', popularity: 56 },
      { korean: '민서', romanization: 'Min-seo', englishSound: 'min-suh', meaning: 'Quick and auspicious', story: 'This name grows like fast bamboo under auspicious stars, representing rapid growth blessed by favorable circumstances.', popularity: 53 },
      { korean: '예지', romanization: 'Ye-ji', englishSound: 'yeh-jee', meaning: 'Beautiful wisdom', story: 'Like the beautiful wisdom of ancient trees, this name represents knowledge that grows more beautiful with age and experience.', popularity: 50 },
      { korean: '지은', romanization: 'Ji-eun', englishSound: 'jee-eun', meaning: 'Wise grace', story: 'This name flows like graceful wisdom through generations, representing knowledge that is passed down with love and care.', popularity: 47 },
      { korean: '하은', romanization: 'Ha-eun', englishSound: 'ha-eun', meaning: 'Great grace', story: 'Like a great tree that provides graceful shelter, this name represents generous beauty that protects and nurtures others.', popularity: 44 },
      { korean: '서연', romanization: 'Seo-yeon', englishSound: 'suh-yun', meaning: 'Auspicious connection', story: 'This name connects like the roots of a forest, representing auspicious relationships that strengthen the whole community.', popularity: 41 },
      { korean: '채린', romanization: 'Chae-rin', englishSound: 'chay-rin', meaning: 'Colorful wisdom', story: 'Like a forest where each tree contributes its own color, this name represents wisdom that comes from embracing diversity.', popularity: 38 },
      // K-pop inspired names
      { korean: '다현', romanization: 'Da-hyun', englishSound: 'da-hyun', meaning: 'Many virtues', story: 'Like a garden with many different virtues blooming together, this name represents someone with diverse talents and moral qualities.', popularity: 88, kpopMember: { group: 'TWICE', memberName: 'Dahyun' } },
      { korean: '채원', romanization: 'Chae-won', englishSound: 'chay-won', meaning: 'Colorful garden', story: 'Like a beautiful garden that blooms with many colors, this name represents someone who brings natural beauty and diverse talents to flourish together.', popularity: 85, kpopMember: { group: 'LE SSERAFIM', memberName: 'Chaewon' } },
      { korean: '찬영', romanization: 'Chan-yeong', englishSound: 'chan-young', meaning: 'Bright prosperity', story: 'Like a tree that prospers with bright energy, this name represents someone who achieves success through positive growth and radiant character.', popularity: 83, kpopMember: { group: 'RIIZE', memberName: 'Chanyoung' } }
    ]
  },
  fire: {
    male: [
      // Most Popular 2024-2025 Fire Element Names
      { korean: '하준', romanization: 'Ha-jun', englishSound: 'ha-joon', meaning: 'Summer and talented', story: 'This name captures the peak of summer\'s warmth and energy, representing someone who shines brightest when helping others.', popularity: 98 },
      { korean: '시우', romanization: 'Si-woo', englishSound: 'see-woo', meaning: 'Beginning rain', story: 'This name represents the first rain that breaks a drought, bringing hope and renewal with passionate energy.', popularity: 94 },
      { korean: '도윤', romanization: 'Do-yoon', englishSound: 'do-yoon', meaning: 'Moral and prosperous', story: 'Like a flame that burns bright and clean, this name embodies ethical leadership and success through integrity.', popularity: 90 },
      { korean: '지훈', romanization: 'Ji-hoon', englishSound: 'jee-hoon', meaning: 'Wise and meritorious', story: 'Like a lighthouse that guides ships safely to shore, this name represents wisdom that illuminates the path for others.', popularity: 86 },
      { korean: '태민', romanization: 'Tae-min', englishSound: 'tay-min', meaning: 'Great and quick', story: 'This name burns like a bright flame that moves swiftly, representing greatness achieved through passionate dedication.', popularity: 82 },
      { korean: '현수', romanization: 'Hyun-soo', englishSound: 'hyun-soo', meaning: 'Virtuous and excellent', story: 'Like a flame that burns with moral purpose, this name represents excellence that lights the way for ethical action.', popularity: 78 },
      { korean: '정우', romanization: 'Jeong-woo', englishSound: 'jung-woo', meaning: 'Righteous and excellent', story: 'This name blazes like righteous fire that purifies and protects, representing strength used for noble purposes.', popularity: 74 },
      { korean: '승민', romanization: 'Seung-min', englishSound: 'seung-min', meaning: 'Victory and quick', story: 'Like lightning that strikes with perfect timing, this name represents quick victories achieved through inner fire.', popularity: 70 },
      { korean: '동현', romanization: 'Dong-hyun', englishSound: 'dong-hyun', meaning: 'Eastern virtue', story: 'This name rises like the sun from the east, representing virtue that brings new light to each day.', popularity: 66 },
      { korean: '민수', romanization: 'Min-soo', englishSound: 'min-soo', meaning: 'Quick and excellent', story: 'Like a flame that dances with swift excellence, this name represents agility combined with passionate mastery.', popularity: 62 },
      { korean: '지환', romanization: 'Ji-hwan', englishSound: 'jee-hwan', meaning: 'Wise and bright', story: 'This name shines like wise fire that illuminates without burning, representing intelligence that warms and enlightens.', popularity: 58 },
      { korean: '태준', romanization: 'Tae-jun', englishSound: 'tay-joon', meaning: 'Great and talented', story: 'Like a great bonfire that draws people together, this name represents talent that creates community and warmth.', popularity: 54 },
      { korean: '정민', romanization: 'Jeong-min', englishSound: 'jung-min', meaning: 'Righteous and quick', story: 'This name burns like righteous flame that acts swiftly for justice, representing quick moral action.', popularity: 50 },
      { korean: '승우', romanization: 'Seung-woo', englishSound: 'seung-woo', meaning: 'Victory and excellent', story: 'Like a triumphant flame that never dims, this name represents excellent victories that inspire others to achieve.', popularity: 46 },
      { korean: '현진', romanization: 'Hyun-jin', englishSound: 'hyun-jin', meaning: 'Virtuous and precious', story: 'This name glows like precious fire that burns with virtue, representing value that comes from moral character.', popularity: 42 },
      { korean: '동민', romanization: 'Dong-min', englishSound: 'dong-min', meaning: 'Eastern quick', story: 'Like the swift sunrise that brings hope each morning, this name represents quick action that brings renewal and energy.', popularity: 38 },
      { korean: '태우', romanization: 'Tae-woo', englishSound: 'tay-woo', meaning: 'Great and excellent', story: 'This name burns like a great flame that achieves excellence, representing passionate pursuit of worthy goals.', popularity: 34 },
      { korean: '정현', romanization: 'Jeong-hyun', englishSound: 'jung-hyun', meaning: 'Righteous and virtuous', story: 'Like a sacred flame that burns with pure virtue, this name represents righteousness that guides and protects.', popularity: 30 },
      { korean: '승현', romanization: 'Seung-hyun', englishSound: 'seung-hyun', meaning: 'Victory and virtuous', story: 'This name blazes like victorious fire that wins through virtue, representing triumph achieved through moral strength.', popularity: 26 },
      { korean: '지성', romanization: 'Ji-seong', englishSound: 'jee-sung', meaning: 'Wise and sincere', story: 'Like sincere fire that burns with honest wisdom, this name represents knowledge gained through passionate dedication.', popularity: 22 },
      // K-pop inspired names  
      { korean: '지민', romanization: 'Ji-min', englishSound: 'jee-min', meaning: 'Wise and quick', story: 'Like quick fire that burns with wisdom, this name represents intelligent passion and the ability to inspire others with bright energy.', popularity: 95, kpopMember: { group: 'BTS', memberName: 'Jimin' } },
      { korean: '정국', romanization: 'Jeong-guk', englishSound: 'jung-gook', meaning: 'Righteous country', story: 'This name burns like righteous fire that protects the country, representing patriotic passion and strength that defends what is precious.', popularity: 92, kpopMember: { group: 'BTS', memberName: 'Jungkook' } },
      { korean: '호석', romanization: 'Ho-seok', englishSound: 'ho-suk', meaning: 'Great stone', story: 'Like a great stone heated by fire, this name represents solid strength combined with passionate energy and joyful spirit.', popularity: 89, kpopMember: { group: 'BTS', memberName: 'J-Hope' } }
    ],
    female: [
      // Most Popular 2024-2025 Fire Element Names
      { korean: '하은', romanization: 'Ha-eun', englishSound: 'ha-eun', meaning: 'Grace from above', story: 'Like sunlight breaking through clouds, this name represents divine grace that illuminates and warms everything it touches.', popularity: 96 },
      { korean: '서윤', romanization: 'Seo-yoon', englishSound: 'suh-yoon', meaning: 'Western prosperity', story: 'This name embodies the warmth of a sunset that promises a bright tomorrow, bringing abundance and joy.', popularity: 92 },
      { korean: '예린', romanization: 'Ye-rin', englishSound: 'yeh-rin', meaning: 'Beautiful and wise', story: 'Like a campfire that draws people together, this name represents beauty that comes from inner wisdom and warmth.', popularity: 88 },
      { korean: '지아', romanization: 'Ji-ah', englishSound: 'jee-ah', meaning: 'Wise and beautiful', story: 'This name glows like wise flame that beautifies everything around it, representing intelligence that creates harmony.', popularity: 84 },
      { korean: '소연', romanization: 'So-yeon', englishSound: 'so-yun', meaning: 'Small lotus', story: 'Like a delicate flame that burns steadily, this name represents gentle strength that endures through all seasons.', popularity: 80 },
      { korean: '예나', romanization: 'Ye-na', englishSound: 'yeh-na', meaning: 'Beautiful me', story: 'This name shines like confident fire that celebrates inner beauty, representing self-acceptance that inspires others.', popularity: 76 },
      { korean: '지연', romanization: 'Ji-yeon', englishSound: 'jee-yun', meaning: 'Wise connection', story: 'Like fire that connects hearts across distances, this name represents wisdom that builds meaningful relationships.', popularity: 72 },
      { korean: '하린', romanization: 'Ha-rin', englishSound: 'ha-rin', meaning: 'Beautiful sky', story: 'This name blazes like the beautiful fire of dawn, representing hope that lights up the entire horizon.', popularity: 68 },
      { korean: '다은', romanization: 'Da-eun', englishSound: 'da-eun', meaning: 'Many graces', story: 'Like a flame that has many beautiful colors, this name represents abundant grace expressed in countless ways.', popularity: 64 },
      { korean: '서현', romanization: 'Seo-hyun', englishSound: 'suh-hyun', meaning: 'Auspicious virtue', story: 'This name burns like virtuous fire under auspicious stars, representing moral character blessed with good fortune.', popularity: 60 },
      { korean: '지현', romanization: 'Ji-hyun', englishSound: 'jee-hyun', meaning: 'Wise and virtuous', story: 'Like sacred fire that burns with wise virtue, this name represents moral wisdom that lights the way forward.', popularity: 56 },
      { korean: '예원', romanization: 'Ye-won', englishSound: 'yeh-won', meaning: 'Beautiful source', story: 'This name flows like beautiful fire from its source, representing inner beauty that radiates outward naturally.', popularity: 52 },
      { korean: '소희', romanization: 'So-hui', englishSound: 'so-hee', meaning: 'Pure and bright joy', story: 'Like a cheerful flame that brings joy to small moments, this name represents happiness found in life\'s simple pleasures.', popularity: 48 },
      { korean: '다현', romanization: 'Da-hyun', englishSound: 'da-hyun', meaning: 'Many virtues', story: 'This name burns like fire that displays many virtuous colors, representing character rich in moral qualities.', popularity: 44 },
      { korean: '지원', romanization: 'Ji-won', englishSound: 'jee-won', meaning: 'Wise source', story: 'Like the wise fire that becomes a source of warmth for others, this name represents knowledge that nurtures community.', popularity: 40 },
      { korean: '예진', romanization: 'Ye-jin', englishSound: 'yeh-jin', meaning: 'Beautiful precious', story: 'This name glows like precious fire that reveals inner beauty, representing value that comes from authentic self-expression.', popularity: 36 },
      { korean: '하영', romanization: 'Ha-yeong', englishSound: 'ha-young', meaning: 'Great prosperity', story: 'Like prosperous fire that brings abundance, this name represents success that lights the way for others to follow.', popularity: 32 },
      { korean: '서영', romanization: 'Seo-yeong', englishSound: 'suh-young', meaning: 'Auspicious prosperity', story: 'This name blazes like fire blessed with prosperity, representing abundance that comes through favorable circumstances.', popularity: 28 },
      { korean: '지혜', romanization: 'Ji-hye', englishSound: 'jee-hye', meaning: 'Intelligent wisdom', story: 'Like the pure fire of ancient wisdom, this name represents knowledge that burns brightly across generations.', popularity: 24 },
      { korean: '다영', romanization: 'Da-yeong', englishSound: 'da-young', meaning: 'Many prosperities', story: 'This name burns like fire that creates prosperity in many forms, representing abundant success in all endeavors.', popularity: 20 },
      // K-pop inspired names
      { korean: '지수', romanization: 'Ji-soo', englishSound: 'jee-soo', meaning: 'Wise beautiful', story: 'Like wise fire that creates beauty, this name represents intelligence that shines with natural elegance and warm charisma.', popularity: 93, kpopMember: { group: 'BLACKPINK', memberName: 'Jisoo' } },
      { korean: '나연', romanization: 'Na-yeon', englishSound: 'na-yun', meaning: 'My connection', story: 'Like warm fire that creates meaningful connections, this name represents someone who brings people together with natural charm and bright energy.', popularity: 90, kpopMember: { group: 'TWICE', memberName: 'Nayeon' } },
      { korean: '정연', romanization: 'Jeong-yeon', englishSound: 'jung-yun', meaning: 'Righteous connection', story: 'This name burns like righteous fire that forms pure connections, representing honest relationships built on moral strength and warm sincerity.', popularity: 87, kpopMember: { group: 'TWICE', memberName: 'Jeongyeon' } },
      { korean: '정한', romanization: 'Jeong-han', englishSound: 'jung-han', meaning: 'Righteous one', story: 'Like righteous fire that burns with singular purpose, this name represents someone who stands for what is right with passionate dedication and moral clarity.', popularity: 85, kpopMember: { group: 'SEVENTEEN', memberName: 'Jeonghan' } },
      { korean: '도겸', romanization: 'Do-kyeom', englishSound: 'do-kyum', meaning: 'Path modest', story: 'This name burns like modest fire that lights the path, representing humble leadership that guides others through passionate service and sincere dedication.', popularity: 82, kpopMember: { group: 'SEVENTEEN', memberName: 'DK' } },
      { korean: '소연', romanization: 'So-yeon', englishSound: 'so-yun', meaning: 'Small connection', story: 'Like gentle fire that creates small but meaningful connections, this name represents someone who builds intimate relationships through warm, sincere passion.', popularity: 88, kpopMember: { group: '(G)I-DLE', memberName: 'Soyeon' } }
    ]
  },
  earth: {
    male: [
      // Most Popular 2024-2025 Earth Element Names
      { korean: '이준', romanization: 'Yi-jun', englishSound: 'ee-joon', meaning: 'Second talented', story: 'Like a mountain spring that feeds countless streams, this name represents someone who provides for and nurtures others.', popularity: 100 },
      { korean: '주원', romanization: 'Ju-won', englishSound: 'joo-won', meaning: 'Main source', story: 'This name flows like the steady source that feeds a great river, representing reliable strength that supports entire communities.', popularity: 96 },
      { korean: '우진', romanization: 'Woo-jin', englishSound: 'woo-jin', meaning: 'Rain and truth', story: 'Like fertile soil that receives rain and produces truth in the form of abundant harvest, this name represents honest productivity.', popularity: 92 },
      { korean: '예준', romanization: 'Ye-jun', englishSound: 'yeh-joon', meaning: 'Polite and talented', story: 'Like a master craftsman who creates with humble precision, this name represents refined talent grounded in respect.', popularity: 88 },
      { korean: '성현', romanization: 'Seong-hyun', englishSound: 'sung-hyun', meaning: 'Holy virtue', story: 'This name stands like a sacred mountain that embodies virtue, representing moral character that provides guidance and stability.', popularity: 84 },
      { korean: '민호', romanization: 'Min-ho', englishSound: 'min-ho', meaning: 'Quick and great', story: 'Like rich earth that quickly responds to the seasons, this name represents greatness that grows from responsive wisdom.', popularity: 80 },
      { korean: '준영', romanization: 'Jun-yeong', englishSound: 'joon-young', meaning: 'Talented and prosperous', story: 'This name builds like prosperous earth that supports talented growth, representing success rooted in solid foundations.', popularity: 76 },
      { korean: '윤수', romanization: 'Yoon-soo', englishSound: 'yoon-soo', meaning: 'Prosperous excellence', story: 'Like fertile ground that produces excellent harvest, this name represents prosperity achieved through steady, quality effort.', popularity: 72 },
      { korean: '상우', romanization: 'Sang-woo', englishSound: 'sang-woo', meaning: 'Mutual excellence', story: 'This name connects like earth that supports all growth mutually, representing excellence that lifts everyone up together.', popularity: 68 },
      { korean: '진우', romanization: 'Jin-woo', englishSound: 'jin-woo', meaning: 'Precious excellence', story: 'Like precious earth that contains valuable minerals, this name represents excellence that becomes more valuable over time.', popularity: 64 },
      { korean: '성진', romanization: 'Seong-jin', englishSound: 'sung-jin', meaning: 'Holy precious', story: 'This name stands like sacred ground that holds precious treasures, representing character that treasures what is truly valuable.', popularity: 60 },
      { korean: '준서', romanization: 'Jun-seo', englishSound: 'joon-suh', meaning: 'Talented auspicious', story: 'Like auspicious earth that nurtures talented growth, this name represents skill blessed with favorable conditions.', popularity: 56 },
      { korean: '민재', romanization: 'Min-jae', englishSound: 'min-jay', meaning: 'Quick talent', story: 'This name grows like quick earth that immediately supports new talent, representing responsive nurturing of emerging gifts.', popularity: 52 },
      { korean: '윤호', romanization: 'Yoon-ho', englishSound: 'yoon-ho', meaning: 'Prosperous great', story: 'Like great earth that creates lasting prosperity, this name represents achievements that benefit many generations.', popularity: 48 },
      { korean: '상민', romanization: 'Sang-min', englishSound: 'sang-min', meaning: 'Mutual quick', story: 'This name connects like earth that quickly responds to mutual needs, representing swift cooperation and shared success.', popularity: 44 },
      { korean: '진호', romanization: 'Jin-ho', englishSound: 'jin-ho', meaning: 'Precious great', story: 'Like precious earth that supports great growth, this name represents value that creates lasting greatness for the community.', popularity: 40 },
      { korean: '성수', romanization: 'Seong-soo', englishSound: 'sung-soo', meaning: 'Holy excellence', story: 'This name stands like holy ground that produces excellent fruit, representing character that achieves sacred excellence.', popularity: 36 },
      { korean: '준민', romanization: 'Jun-min', englishSound: 'joon-min', meaning: 'Talented quick', story: 'Like earth that quickly recognizes and nurtures talent, this name represents swift recognition and development of gifts.', popularity: 32 },
      { korean: '윤진', romanization: 'Yoon-jin', englishSound: 'yoon-jin', meaning: 'Prosperous precious', story: 'This name treasures like prosperous earth that holds precious resources, representing abundance that values what matters most.', popularity: 28 },
      { korean: '상호', romanization: 'Sang-ho', englishSound: 'sang-ho', meaning: 'Mutual great', story: 'Like earth that supports mutual greatness in all who dwell upon it, this name represents shared achievement and community success.', popularity: 24 },
      // K-pop inspired names
      { korean: '승민', romanization: 'Seung-min', englishSound: 'seung-min', meaning: 'Victory and quick', story: 'Like earth that achieves victory through steady persistence, this name represents success built on solid foundations and determined effort.', popularity: 86, kpopMember: { group: 'Stray Kids', memberName: 'Seungmin' } },
      { korean: '현진', romanization: 'Hyun-jin', englishSound: 'hyun-jin', meaning: 'Virtuous precious', story: 'This name stands like precious earth that embodies virtue, representing moral character that becomes more valuable through time and trials.', popularity: 83, kpopMember: { group: 'Stray Kids', memberName: 'Hyunjin' } },
      { korean: '한', romanization: 'Han', englishSound: 'han', meaning: 'Great and vast', story: 'Like the great earth that supports all life, this name represents someone with vast potential and the ability to provide stable foundation for others.', popularity: 80, kpopMember: { group: 'Stray Kids', memberName: 'Han' } },
      { korean: '민규', romanization: 'Min-gyu', englishSound: 'min-gyu', meaning: 'Quick standard', story: 'Like earth that quickly sets the standard for growth, this name represents someone who establishes excellent examples through steady, reliable action.', popularity: 87, kpopMember: { group: 'SEVENTEEN', memberName: 'Mingyu' } },
      { korean: '성찬', romanization: 'Seong-chan', englishSound: 'sung-chan', meaning: 'Holy bright', story: 'Like sacred earth that shines with holy brightness, this name represents someone who illuminates others through grounded spiritual strength and moral clarity.', popularity: 84, kpopMember: { group: 'RIIZE', memberName: 'Seungchan' } }
    ],
    female: [
      // Most Popular 2024-2025 Earth Element Names  
      { korean: '이서', romanization: 'Yi-seo', englishSound: 'ee-suh', meaning: 'Second auspicious', story: 'Like gentle earth that brings auspicious growth, this name represents grace that creates favorable conditions for others to flourish.', popularity: 100 },
      { korean: '수아', romanization: 'Soo-ah', englishSound: 'soo-ah', meaning: 'Beautiful like water', story: 'This name flows like a gentle stream that carves beautiful valleys, representing quiet strength that shapes the world.', popularity: 96 },
      { korean: '지유', romanization: 'Ji-yoo', englishSound: 'jee-yoo', meaning: 'Wise and gentle', story: 'Like rich earth that nurtures seeds with wise patience, this name embodies wisdom that comes from gentle nurturing.', popularity: 92 },
      { korean: '소율', romanization: 'So-yul', englishSound: 'so-yul', meaning: 'Small and rhythmic', story: 'Like the steady heartbeat of the earth itself, this name represents someone who brings harmony and natural rhythm to life.', popularity: 88 },
      { korean: '서아', romanization: 'Seo-ah', englishSound: 'suh-ah', meaning: 'Auspicious beautiful', story: 'This name blooms like auspicious earth that produces beautiful flowers, representing beauty blessed with good fortune.', popularity: 84 },
      { korean: '유나', romanization: 'Yu-na', englishSound: 'yu-na', meaning: 'Abundant me', story: 'Like abundant earth that generously supports all growth, this name represents self-confidence that nurtures abundance in others.', popularity: 80 },
      { korean: '채영', romanization: 'Chae-yeong', englishSound: 'chay-young', meaning: 'Colorful prosperity', story: 'This name flourishes like colorful earth that produces prosperous harvests, representing diverse talents that create abundance.', popularity: 76 },
      { korean: '수연', romanization: 'Soo-yeon', englishSound: 'soo-yun', meaning: 'Beautiful connection', story: 'Like earth that beautifully connects all living things, this name represents relationships that create harmony and mutual support.', popularity: 72 },
      { korean: '은서', romanization: 'Eun-seo', englishSound: 'eun-suh', meaning: 'Kindness auspicious', story: 'This name nurtures like kind earth blessed with auspicious seasons, representing generosity that brings good fortune to all.', popularity: 68 },
      { korean: '예서', romanization: 'Ye-seo', englishSound: 'yeh-suh', meaning: 'Beautiful auspicious', story: 'Like beautiful earth under auspicious stars, this name represents grace that is blessed with favorable circumstances.', popularity: 64 },
      { korean: '수민', romanization: 'Soo-min', englishSound: 'soo-min', meaning: 'Beautiful quick', story: 'This name responds like beautiful earth that quickly adapts to changes, representing grace that flows smoothly through life\'s seasons.', popularity: 60 },
      { korean: '지연', romanization: 'Ji-yeon', englishSound: 'jee-yun', meaning: 'Wise connection', story: 'Like wise earth that connects forest to meadow, this name represents intelligence that builds meaningful bridges between people.', popularity: 56 },
      { korean: '유진', romanization: 'Yu-jin', englishSound: 'yu-jin', meaning: 'Abundant precious', story: 'This name treasures like abundant earth that holds precious minerals, representing generosity that recognizes true value.', popularity: 52 },
      { korean: '채은', romanization: 'Chae-eun', englishSound: 'chay-eun', meaning: 'Colorful grace', story: 'Like colorful earth that shows grace in every season, this name represents diverse beauty that brings harmony to all situations.', popularity: 48 },
      { korean: '수현', romanization: 'Soo-hyun', englishSound: 'soo-hyun', meaning: 'Beautiful virtue', story: 'This name stands like beautiful earth that embodies virtue, representing moral beauty that inspires and guides others.', popularity: 44 },
      { korean: '은지', romanization: 'Eun-ji', englishSound: 'eun-jee', meaning: 'Kindness wisdom', story: 'Like kind earth that holds ancient wisdom, this name represents compassion that comes from deep understanding.', popularity: 40 },
      { korean: '예은', romanization: 'Ye-eun', englishSound: 'yeh-eun', meaning: 'Beautiful grace', story: 'This name flows like beautiful earth that shows grace in all its forms, representing elegance that comes from inner strength.', popularity: 36 },
      { korean: '수정', romanization: 'Soo-jeong', englishSound: 'soo-jung', meaning: 'Beautiful pure', story: 'Like pure earth that creates crystal-clear springs, this name represents beauty that comes from authentic purity of heart.', popularity: 32 },
      { korean: '지수', romanization: 'Ji-soo', englishSound: 'jee-soo', meaning: 'Wise beautiful', story: 'This name shines like wise earth that creates beautiful landscapes, representing intelligence that manifests as natural beauty.', popularity: 28 },
      { korean: '유경', romanization: 'Yu-kyung', englishSound: 'yu-kyung', meaning: 'Abundant respect', story: 'Like abundant earth that commands natural respect, this name represents generosity that earns honor through consistent giving.', popularity: 24 },
      // K-pop inspired names
      { korean: '미나', romanization: 'Mi-na', englishSound: 'mee-na', meaning: 'Beautiful me', story: 'Like beautiful earth that nurtures self-acceptance, this name represents inner beauty that grows from solid self-confidence and natural grace.', popularity: 87, kpopMember: { group: 'TWICE', memberName: 'Mina' } },
      { korean: '채영', romanization: 'Chae-yeong', englishSound: 'chay-young', meaning: 'Colorful prosperity', story: 'This name flourishes like colorful earth that creates prosperity, representing diverse talents that build abundance through creative expression.', popularity: 84, kpopMember: { group: 'TWICE', memberName: 'Chaeyoung' } },
      { korean: '지효', romanization: 'Ji-hyo', englishSound: 'jee-hyo', meaning: 'Wise filial piety', story: 'Like wise earth that honors family traditions, this name represents intelligence combined with respect for elders and cultural heritage.', popularity: 81, kpopMember: { group: 'TWICE', memberName: 'Jihyo' } }
    ]
  },
  metal: {
    male: [
      // Most Popular 2024-2025 Metal Element Names
      { korean: '서준', romanization: 'Seo-jun', englishSound: 'suh-joon', meaning: 'Western talent', story: 'Like a perfectly forged blade that reflects light, this name represents talent that cuts through challenges with precision and honor.', popularity: 93 },
      { korean: '태윤', romanization: 'Tae-yoon', englishSound: 'tay-yoon', meaning: 'Great prosperity', story: 'This name embodies the strength of precious metal that becomes more valuable under pressure, bringing lasting success.', popularity: 89 },
      { korean: '현우', romanization: 'Hyun-woo', englishSound: 'hyun-woo', meaning: 'Wise and excellent', story: 'Like a master swordsmith who combines wisdom with skill, this name represents excellence achieved through disciplined practice.', popularity: 85 },
      { korean: '승호', romanization: 'Seung-ho', englishSound: 'seung-ho', meaning: 'Victory and great', story: 'This name rings like victorious metal that achieves greatness, representing triumph earned through persistent effort and integrity.', popularity: 81 },
      { korean: '정호', romanization: 'Jeong-ho', englishSound: 'jung-ho', meaning: 'Righteous great', story: 'Like righteous metal that stands firm for justice, this name represents greatness built on moral principles and honest action.', popularity: 77 },
      { korean: '민철', romanization: 'Min-chul', englishSound: 'min-chul', meaning: 'Quick iron', story: 'This name strikes like quick iron that shapes itself perfectly, representing adaptability combined with inner strength and determination.', popularity: 73 },
      { korean: '준철', romanization: 'Jun-chul', englishSound: 'joon-chul', meaning: 'Talented iron', story: 'Like talented metal that can be forged into any masterpiece, this name represents versatile skill guided by strong principles.', popularity: 69 },
      { korean: '성호', romanization: 'Seong-ho', englishSound: 'sung-ho', meaning: 'Holy great', story: 'This name stands like sacred metal that achieves true greatness, representing character that pursues excellence through righteous means.', popularity: 65 },
      { korean: '진석', romanization: 'Jin-seok', englishSound: 'jin-suk', meaning: 'Precious stone', story: 'Like precious metal formed into a perfect stone, this name represents value that comes from pressure transformed into strength.', popularity: 61 },
      { korean: '동현', romanization: 'Dong-hyun', englishSound: 'dong-hyun', meaning: 'Eastern virtue', story: 'This name shines like eastern metal that embodies virtue, representing moral character that brings new light to each situation.', popularity: 57 },
      { korean: '철민', romanization: 'Chul-min', englishSound: 'chul-min', meaning: 'Iron quick', story: 'Like iron that responds quickly to the smith\'s hammer, this name represents strength that adapts swiftly to create something beautiful.', popularity: 53 },
      { korean: '승재', romanization: 'Seung-jae', englishSound: 'seung-jay', meaning: 'Victory talent', story: 'This name conquers like victorious metal that demonstrates talent, representing skill that achieves success through determined practice.', popularity: 49 },
      { korean: '정민', romanization: 'Jeong-min', englishSound: 'jung-min', meaning: 'Righteous quick', story: 'Like righteous metal that acts swiftly for justice, this name represents quick moral action guided by strong principles.', popularity: 45 },
      { korean: '현철', romanization: 'Hyun-chul', englishSound: 'hyun-chul', meaning: 'Virtuous iron', story: 'This name forges like virtuous metal that creates lasting strength, representing character that builds excellence through ethical practice.', popularity: 41 },
      { korean: '승철', romanization: 'Seung-chul', englishSound: 'seung-chul', meaning: 'Victory iron', story: 'Like victorious metal that wins through strength, this name represents triumph achieved through persistent effort and unwavering determination.', popularity: 37 },
      { korean: '정석', romanization: 'Jeong-seok', englishSound: 'jung-suk', meaning: 'Righteous stone', story: 'This name stands like righteous metal formed into enduring stone, representing moral character that creates lasting positive impact.', popularity: 33 },
      { korean: '진호', romanization: 'Jin-ho', englishSound: 'jin-ho', meaning: 'Precious great', story: 'Like precious metal that achieves true greatness, this name represents value that increases through dedication to worthy purposes.', popularity: 29 },
      { korean: '동철', romanization: 'Dong-chul', englishSound: 'dong-chul', meaning: 'Eastern iron', story: 'This name rises like eastern metal that brings new strength, representing power that comes with the dawn of new possibilities.', popularity: 25 },
      { korean: '성민', romanization: 'Seong-min', englishSound: 'sung-min', meaning: 'Holy quick', story: 'Like sacred metal that responds quickly to noble purposes, this name represents swift action guided by higher principles.', popularity: 21 },
      { korean: '철호', romanization: 'Chul-ho', englishSound: 'chul-ho', meaning: 'Iron great', story: 'This name endures like iron that achieves greatness through time, representing strength that creates lasting excellence for future generations.', popularity: 17 },
      // K-pop inspired names
      { korean: '방찬', romanization: 'Bang-chan', englishSound: 'bang-chan', meaning: 'Room bright', story: 'Like bright metal that illuminates every room, this name represents leadership that brings clarity and warmth to any environment.', popularity: 88, kpopMember: { group: 'Stray Kids', memberName: 'Bang Chan' } },
      { korean: '창빈', romanization: 'Chang-bin', englishSound: 'chang-bin', meaning: 'Spear refined', story: 'Like refined metal forged into a perfect spear, this name represents focused strength and precision in achieving goals.', popularity: 82, kpopMember: { group: 'Stray Kids', memberName: 'Changbin' } },
      { korean: '승한', romanization: 'Seung-han', englishSound: 'seung-han', meaning: 'Victory one', story: 'Like victorious metal that stands as one, this name represents unified strength that achieves victory through determination and focused purpose.', popularity: 86, kpopMember: { group: 'RIIZE', memberName: 'Seunghan' } },
      { korean: '선우', romanization: 'Seon-woo', englishSound: 'sun-woo', meaning: 'Good excellent', story: 'Like excellent metal refined through goodness, this name represents someone who achieves excellence through moral character and kind strength.', popularity: 84, kpopMember: { group: 'THE BOYZ', memberName: 'Sunwoo' } }
    ],
    female: [
      // Most Popular 2024-2025 Metal Element Names
      { korean: '하린', romanization: 'Ha-rin', englishSound: 'ha-rin', meaning: 'Beautiful sky', story: 'Like silver stars that guide travelers through dark nights, this name represents beauty that provides direction and inspiration.', popularity: 91 },
      { korean: '은서', romanization: 'Eun-seo', englishSound: 'eun-suh', meaning: 'Silver kindness', story: 'This name shines like polished silver, representing kindness that is both precious and enduring, refined through life\'s challenges.', popularity: 87 },
      { korean: '유진', romanization: 'Yoo-jin', englishSound: 'yoo-jin', meaning: 'Gentle and precious', story: 'Like a delicate golden ornament that protects treasures, this name embodies gentle strength that guards what is valuable.', popularity: 83 },
      { korean: '소영', romanization: 'So-yeong', englishSound: 'so-young', meaning: 'Small prosperity', story: 'This name glows like small precious metal that creates prosperity, representing modest excellence that builds lasting abundance.', popularity: 79 },
      { korean: '정은', romanization: 'Jeong-eun', englishSound: 'jung-eun', meaning: 'Righteous kindness', story: 'Like righteous metal that shows kindness through strength, this name represents compassion guided by moral principles.', popularity: 75 },
      { korean: '혜린', romanization: 'Hye-rin', englishSound: 'hye-rin', meaning: 'Wise beautiful', story: 'This name shines like wise metal that creates beauty, representing intelligence that manifests as elegant strength and grace.', popularity: 71 },
      { korean: '수정', romanization: 'Soo-jeong', englishSound: 'soo-jung', meaning: 'Beautiful crystal', story: 'Like pure crystal formed by patient pressure, this name represents beauty that comes from clarity achieved through perseverance.', popularity: 67 },
      { korean: '진영', romanization: 'Jin-yeong', englishSound: 'jin-young', meaning: 'Precious prosperity', story: 'This name prospers like precious metal that creates abundance, representing value that multiplies when shared with others.', popularity: 63 },
      { korean: '은지', romanization: 'Eun-ji', englishSound: 'eun-jee', meaning: 'Silver wisdom', story: 'Like silver that holds ancient wisdom, this name represents knowledge that becomes more valuable with age and experience.', popularity: 59 },
      { korean: '정아', romanization: 'Jeong-ah', englishSound: 'jung-ah', meaning: 'Righteous beautiful', story: 'This name beautifies like righteous metal that creates lasting elegance, representing beauty rooted in strong moral character.', popularity: 55 },
      { korean: '소정', romanization: 'So-jeong', englishSound: 'so-jung', meaning: 'Small crystal', story: 'Like a small crystal that refracts pure light, this name represents modest perfection that illuminates everything around it.', popularity: 51 },
      { korean: '혜진', romanization: 'Hye-jin', englishSound: 'hye-jin', meaning: 'Wise precious', story: 'This name treasures like wise metal that recognizes true value, representing intelligence that appreciates what is genuinely precious.', popularity: 47 },
      { korean: '수진', romanization: 'Soo-jin', englishSound: 'soo-jin', meaning: 'Beautiful precious', story: 'Like beautiful metal that holds precious meaning, this name represents elegance that comes from valuing inner beauty.', popularity: 43 },
      { korean: '은영', romanization: 'Eun-yeong', englishSound: 'eun-young', meaning: 'Silver prosperity', story: 'This name prospers like silver that creates lasting abundance, representing success that comes through consistent excellence and integrity.', popularity: 39 },
      { korean: '정현', romanization: 'Jeong-hyun', englishSound: 'jung-hyun', meaning: 'Righteous virtue', story: 'Like righteous metal that embodies virtue, this name represents moral character that shines through principled action.', popularity: 35 },
      { korean: '소진', romanization: 'So-jin', englishSound: 'so-jin', meaning: 'Small precious', story: 'This name values like small precious metal that holds great worth, representing the understanding that true value comes in many forms.', popularity: 31 },
      { korean: '혜영', romanization: 'Hye-yeong', englishSound: 'hye-young', meaning: 'Wise prosperity', story: 'Like wise metal that creates prosperity through intelligence, this name represents success achieved through thoughtful planning and action.', popularity: 27 },
      { korean: '수은', romanization: 'Soo-eun', englishSound: 'soo-eun', meaning: 'Beautiful silver', story: 'This name flows like beautiful silver that adapts perfectly, representing grace that finds the right form for every situation.', popularity: 23 },
      { korean: '진아', romanization: 'Jin-ah', englishSound: 'jin-ah', meaning: 'Precious beautiful', story: 'Like precious metal that creates lasting beauty, this name represents value that becomes more beautiful with time and care.', popularity: 19 },
      { korean: '정인', romanization: 'Jeong-in', englishSound: 'jung-in', meaning: 'Righteous person', story: 'This name stands like righteous metal that forms a complete person, representing character that embodies integrity in all aspects of life.', popularity: 15 },
      // K-pop inspired names
      { korean: '예지', romanization: 'Ye-ji', englishSound: 'yeh-jee', meaning: 'Beautiful wisdom', story: 'Like precious metal that holds beautiful wisdom, this name represents intelligence that shines with elegant strength and refined character.', popularity: 89, kpopMember: { group: 'ITZY', memberName: 'Yeji' } },
      { korean: '류진', romanization: 'Ryu-jin', englishSound: 'ryu-jin', meaning: 'Dragon precious', story: 'This name soars like a dragon made of precious metal, representing powerful charisma combined with valuable inner strength.', popularity: 86, kpopMember: { group: 'ITZY', memberName: 'Ryujin' } },
      { korean: '채령', romanization: 'Chae-ryeong', englishSound: 'chay-ryung', meaning: 'Colorful bell', story: 'Like a colorful metal bell that creates beautiful music, this name represents artistic expression that brings harmony and joy to others.', popularity: 83, kpopMember: { group: 'ITZY', memberName: 'Chaeryeong' } },
      { korean: '유나', romanization: 'Yu-na', englishSound: 'yu-na', meaning: 'Abundant me', story: 'Like abundant precious metal that shines with self-confidence, this name represents inner wealth and the courage to be authentically oneself.', popularity: 80, kpopMember: { group: 'ITZY', memberName: 'Yuna' } },
      { korean: '은채', romanization: 'Eun-chae', englishSound: 'eun-chay', meaning: 'Silver colorful', story: 'Like silver that reflects many beautiful colors, this name represents someone who brings out the best qualities in everyone around them with metallic strength and grace.', popularity: 84, kpopMember: { group: 'LE SSERAFIM', memberName: 'Eunchae' } },
      { korean: '유진', romanization: 'Yu-jin', englishSound: 'yu-jin', meaning: 'Gentle precious', story: 'Like gentle precious metal that holds great value, this name represents refined strength combined with precious inner beauty and elegant character.', popularity: 88, kpopMember: { group: 'IVE', memberName: 'Yujin' } }
    ]
  },
  water: {
    male: [
      // Most Popular 2024-2025 Water Element Names
      { korean: '은우', romanization: 'Eun-woo', englishSound: 'eun-woo', meaning: 'Kindness and excellence', story: 'Like a deep ocean that holds countless treasures, this name represents kindness that flows with excellent character and generosity.', popularity: 97 },
      { korean: '준호', romanization: 'Jun-ho', englishSound: 'joon-ho', meaning: 'Talented and great', story: 'This name flows like a mighty river that demonstrates both talent and greatness, representing ability that serves others with wisdom.', popularity: 93 },
      { korean: '민호', romanization: 'Min-ho', englishSound: 'min-ho', meaning: 'Quick and great', story: 'Like a swift river that carves canyons, this name represents intelligence that moves quickly and achieves greatness through adaptability.', popularity: 89 },
      { korean: '지훈', romanization: 'Ji-hoon', englishSound: 'jee-hoon', meaning: 'Wise and meritorious', story: 'Like ancient wisdom flowing through generations, this name embodies knowledge that creates lasting positive change in the world.', popularity: 85 },
      { korean: '현수', romanization: 'Hyun-soo', englishSound: 'hyun-soo', meaning: 'Virtuous excellence', story: 'This name flows like virtuous water that achieves excellence, representing moral character that naturally creates outstanding results.', popularity: 81 },
      { korean: '민수', romanization: 'Min-soo', englishSound: 'min-soo', meaning: 'Quick excellence', story: 'Like quick water that finds the most excellent path, this name represents intelligence that swiftly identifies the best solutions.', popularity: 77 },
      { korean: '준수', romanization: 'Jun-soo', englishSound: 'joon-soo', meaning: 'Talented excellence', story: 'This name demonstrates like talented water that flows with excellence, representing ability that naturally creates beautiful outcomes.', popularity: 73 },
      { korean: '정수', romanization: 'Jeong-soo', englishSound: 'jung-soo', meaning: 'Righteous excellence', story: 'Like righteous water that purifies while achieving excellence, this name represents integrity that creates truly outstanding character.', popularity: 69 },
      { korean: '현호', romanization: 'Hyun-ho', englishSound: 'hyun-ho', meaning: 'Virtuous great', story: 'This name expands like virtuous water that achieves greatness, representing moral character that naturally grows into significant influence.', popularity: 65 },
      { korean: '승수', romanization: 'Seung-soo', englishSound: 'seung-soo', meaning: 'Victory excellence', story: 'Like victorious water that wins through excellence, this name represents success achieved through superior character and persistent effort.', popularity: 61 },
      { korean: '진수', romanization: 'Jin-soo', englishSound: 'jin-soo', meaning: 'Precious excellence', story: 'This name treasures like precious water that displays excellence, representing value that comes from consistently demonstrating quality.', popularity: 57 },
      { korean: '동수', romanization: 'Dong-soo', englishSound: 'dong-soo', meaning: 'Eastern excellence', story: 'Like eastern water that brings excellence with the dawn, this name represents quality that arrives with new opportunities and hope.', popularity: 53 },
      { korean: '민혁', romanization: 'Min-hyuk', englishSound: 'min-hyuk', meaning: 'Quick innovation', story: 'This name innovates like quick water that finds new paths, representing intelligence that creates original solutions to complex challenges.', popularity: 49 },
      { korean: '준혁', romanization: 'Jun-hyuk', englishSound: 'joon-hyuk', meaning: 'Talented innovation', story: 'Like talented water that carves innovative channels, this name represents ability that creates new possibilities and breakthrough solutions.', popularity: 45 },
      { korean: '현준', romanization: 'Hyun-jun', englishSound: 'hyun-joon', meaning: 'Virtuous talent', story: 'This name develops like virtuous water that nurtures talent, representing moral character that helps others discover their abilities.', popularity: 41 },
      { korean: '승호', romanization: 'Seung-ho', englishSound: 'seung-ho', meaning: 'Victory great', story: 'Like victorious water that achieves greatness, this name represents triumph that comes through flowing around obstacles with persistent determination.', popularity: 37 },
      { korean: '정호', romanization: 'Jeong-ho', englishSound: 'jung-ho', meaning: 'Righteous great', story: 'This name expands like righteous water that naturally becomes great, representing integrity that grows into significant positive influence.', popularity: 33 },
      { korean: '진호', romanization: 'Jin-ho', englishSound: 'jin-ho', meaning: 'Precious great', story: 'Like precious water that creates greatness wherever it flows, this name represents value that naturally expands to benefit entire communities.', popularity: 29 },
      { korean: '동호', romanization: 'Dong-ho', englishSound: 'dong-ho', meaning: 'Eastern great', story: 'This name rises like eastern water that brings greatness with each new day, representing excellence that renews and refreshes constantly.', popularity: 25 },
      { korean: '성수', romanization: 'Seong-soo', englishSound: 'sung-soo', meaning: 'Holy excellence', story: 'Like sacred water that embodies excellence, this name represents character that achieves the highest forms of moral and practical excellence.', popularity: 21 },
      // K-pop inspired names
      { korean: '진', romanization: 'Jin', englishSound: 'jin', meaning: 'Precious and genuine', story: 'Like precious water that holds immense value, this name represents someone with rare qualities and the ability to bring beauty and worth to everything they touch.', popularity: 94, kpopMember: { group: 'BTS', memberName: 'Jin' } },
      { korean: '민혁', romanization: 'Min-hyuk', englishSound: 'min-hyuk', meaning: 'Quick innovation', story: 'Like innovative water that quickly finds new paths, this name represents creative intelligence that breaks new ground with fluid adaptation.', popularity: 88, kpopMember: { group: 'BTOB', memberName: 'Minhyuk' } },
      { korean: '원우', romanization: 'Won-woo', englishSound: 'won-woo', meaning: 'Source excellent', story: 'Like excellent water that flows from its source, this name represents someone who maintains excellence while being a source of inspiration and renewal for others.', popularity: 85, kpopMember: { group: 'SEVENTEEN', memberName: 'Wonwoo' } }
    ],
    female: [
      // Most Popular 2024-2025 Water Element Names
      { korean: '윤서', romanization: 'Yoon-seo', englishSound: 'yoon-suh', meaning: 'Prosperous kindness', story: 'Like a spring that never runs dry, this name represents kindness that brings abundance and prosperity to all who encounter it.', popularity: 98 },
      { korean: '수빈', romanization: 'Soo-bin', englishSound: 'soo-bin', meaning: 'Water and refined', story: 'This name flows like crystal-clear water through precious stones, representing purity that has been refined through life\'s journey.', popularity: 94 },
      { korean: '지민', romanization: 'Ji-min', englishSound: 'jee-min', meaning: 'Wise and quick', story: 'Like a mountain stream that knows exactly where to flow, this name embodies quick wisdom that finds the most beautiful path forward.', popularity: 90 },
      { korean: '현서', romanization: 'Hyun-seo', englishSound: 'hyun-suh', meaning: 'Virtuous auspicious', story: 'This name flows like virtuous water under auspicious stars, representing moral character blessed with favorable circumstances.', popularity: 86 },
      { korean: '수현', romanization: 'Soo-hyun', englishSound: 'soo-hyun', meaning: 'Beautiful virtue', story: 'Like beautiful water that embodies virtue, this name represents inner beauty that flows naturally from strong moral character.', popularity: 82 },
      { korean: '민정', romanization: 'Min-jeong', englishSound: 'min-jung', meaning: 'Quick pure', story: 'This name purifies like quick water that immediately cleanses, representing intelligence that swiftly recognizes and embraces what is true.', popularity: 78 },
      { korean: '지수', romanization: 'Ji-soo', englishSound: 'jee-soo', meaning: 'Wise beautiful', story: 'Like wise water that creates beautiful landscapes, this name represents intelligence that naturally manifests as grace and elegance.', popularity: 74 },
      { korean: '혜진', romanization: 'Hye-jin', englishSound: 'hye-jin', meaning: 'Wise precious', story: 'This name treasures like wise water that recognizes precious moments, representing intelligence that values what is truly meaningful in life.', popularity: 70 },
      { korean: '수정', romanization: 'Soo-jeong', englishSound: 'soo-jung', meaning: 'Beautiful pure', story: 'Like pure water that creates crystal formations, this name represents beauty that comes from absolute clarity and authentic transparency.', popularity: 66 },
      { korean: '현정', romanization: 'Hyun-jeong', englishSound: 'hyun-jung', meaning: 'Virtuous pure', story: 'This name purifies like virtuous water that cleanses naturally, representing moral character that brings clarity to complex situations.', popularity: 62 },
      { korean: '민서', romanization: 'Min-seo', englishSound: 'min-suh', meaning: 'Quick auspicious', story: 'Like quick water that flows toward auspicious destinations, this name represents intelligence that naturally moves toward positive outcomes.', popularity: 58 },
      { korean: '지현', romanization: 'Ji-hyun', englishSound: 'jee-hyun', meaning: 'Wise virtue', story: 'This name embodies like wise water that demonstrates virtue, representing knowledge that naturally expresses itself through moral action.', popularity: 54 },
      { korean: '혜수', romanization: 'Hye-soo', englishSound: 'hye-soo', meaning: 'Wise beautiful', story: 'Like wise water that flows with natural beauty, this name represents intelligence that creates elegance in everything it touches.', popularity: 50 },
      { korean: '수민', romanization: 'Soo-min', englishSound: 'soo-min', meaning: 'Beautiful quick', story: 'This name responds like beautiful water that quickly adapts, representing grace that flows smoothly through all of life\'s changing seasons.', popularity: 46 },
      { korean: '현주', romanization: 'Hyun-ju', englishSound: 'hyun-joo', meaning: 'Virtuous jewel', story: 'Like virtuous water that polishes jewels to perfection, this name represents moral character that brings out the best in everything.', popularity: 42 },
      { korean: '민주', romanization: 'Min-ju', englishSound: 'min-joo', meaning: 'Quick jewel', story: 'This name sparkles like quick water that reveals hidden jewels, representing intelligence that swiftly discovers the treasure in every situation.', popularity: 38 },
      { korean: '지영', romanization: 'Ji-yeong', englishSound: 'jee-young', meaning: 'Wise prosperity', story: 'Like wise water that creates prosperity wherever it flows, this name represents knowledge that naturally generates abundance for all.', popularity: 34 },
      { korean: '혜민', romanization: 'Hye-min', englishSound: 'hye-min', meaning: 'Wise quick', story: 'This name flows like wise water that moves with perfect timing, representing intelligence that knows exactly when and how to act.', popularity: 30 },
      { korean: '수영', romanization: 'Soo-yeong', englishSound: 'soo-young', meaning: 'Beautiful prosperity', story: 'Like beautiful water that brings prosperity to the land, this name represents grace that creates abundance through natural beauty and harmony.', popularity: 26 },
      { korean: '현미', romanization: 'Hyun-mi', englishSound: 'hyun-mee', meaning: 'Virtuous beauty', story: 'This name beautifies like virtuous water that enhances everything it touches, representing moral character that creates lasting beauty in the world.', popularity: 22 },
      // K-pop inspired names
      { korean: '해린', romanization: 'Hae-rin', englishSound: 'hay-rin', meaning: 'Ocean beautiful', story: 'Like beautiful ocean water that holds infinite depths, this name represents someone with vast inner beauty and the wisdom of endless horizons.', popularity: 95, kpopMember: { group: 'NewJeans', memberName: 'Haerin' } },
      { korean: '민지', romanization: 'Min-ji', englishSound: 'min-jee', meaning: 'Quick wisdom', story: 'This name flows like quick water that carries wisdom, representing intelligence that moves gracefully and brings insight to every situation.', popularity: 92, kpopMember: { group: 'NewJeans', memberName: 'Minji' } },
      { korean: '혜인', romanization: 'Hye-in', englishSound: 'hye-in', meaning: 'Wise person', story: 'This name embodies like wise water that forms a complete person, representing intelligence that creates harmony between mind, heart, and spirit.', popularity: 86, kpopMember: { group: 'NewJeans', memberName: 'Hyein' } },
      { korean: '원영', romanization: 'Won-yeong', englishSound: 'won-young', meaning: 'Source prosperity', story: 'Like water that flows from a prosperous source, this name represents someone who becomes a source of abundance and success for others through natural grace.', popularity: 89, kpopMember: { group: 'IVE', memberName: 'Wonyoung' } },
      { korean: '주연', romanization: 'Ju-yeon', englishSound: 'joo-yun', meaning: 'Main connection', story: 'Like water that forms the main connection between different sources, this name represents someone who naturally becomes the central link that unites people.', popularity: 87, kpopMember: { group: 'THE BOYZ', memberName: 'Juyeon' } }
    ]
  }
};

// Quick reference statistics
export const NAME_STATISTICS = {
  total: 200,
  maleNames: 100,
  femaleNames: 100,
  byElement: {
    wood: { male: 20, female: 20, total: 40 },
    fire: { male: 20, female: 20, total: 40 },
    earth: { male: 20, female: 20, total: 40 },
    metal: { male: 20, female: 20, total: 40 },
    water: { male: 20, female: 20, total: 40 }
  },
  popularityRange: {
    highest: 100,
    lowest: 15,
    average: 57.5
  }
};